# Generated by Django 5.1.3 on 2024-11-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcioarios',
            name='cargo',
            field=models.CharField(choices=[('Estágio', 'Estágiário'), ('Jr', 'Junior'), ('Pl', 'Pleno'), ('Sr', 'Senior'), ('Tl', 'Tech Lead')], default=2, max_length=100, verbose_name='Cargo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcioarios',
            name='cpf',
            field=models.CharField(default='', max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcioarios',
            name='naturalidade',
            field=models.CharField(max_length=100, verbose_name='Naturalidade'),
        ),
    ]
