# Generated by Django 5.1.3 on 2024-11-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_funcioarios_cargo_alter_funcioarios_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcioarios',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
    ]
