# Generated by Django 4.2.16 on 2024-11-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_funcioarios_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcioarios',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=100, verbose_name='Gênero'),
        ),
    ]
